import streamlit as st
import pandas as pd
from braco_parser import parse_excel_file, parsed_line_to_line_item
from braco_engine import run_selection
from braco_validator import validate_quote
from braco_output import generate_quotation, QuoteConfig

st.set_page_config(page_title="Braco Quotation Engine", layout="wide")

st.title("⚡ Braco Quotation Engine")
st.caption("Upload inquiry → automatic selection → validated quotation")

# ---------------- SIDEBAR ---------------- #
st.sidebar.header("Quote Settings")

quote_ref = st.sidebar.text_input("Quote Reference", "QT0000083")
client_name = st.sidebar.text_input("Client Name", "Client Name")
project_name = st.sidebar.text_input("Project Name", "Project Reference")
section_label = st.sidebar.text_input("Section Label", "16.2")
section_title = st.sidebar.text_input("Section Title", "LT Cable Termination")
discount_pct = st.sidebar.number_input("Discount %", value=46.0)
generated_by = st.sidebar.text_input("Generated By", "Sales Team")
approved_by = st.sidebar.text_input("Approved By", "Director")

use_ai = st.sidebar.toggle("AI Parser (optional)", value=False)
aggregate = st.sidebar.toggle("Aggregate Sheets", value=True)

# ---------------- FILE UPLOAD ---------------- #
uploaded_file = st.file_uploader("Upload BOQ file", type=["xlsx", "xls", "csv"])

if uploaded_file:

    st.success("File uploaded successfully")

    # ---------------- PARSE ---------------- #
    import tempfile  with tempfile.NamedTemporaryFile(delete=False, suffix=".xlsx") as tmp:     tmp.write(uploaded_file.getvalue())     temp_path = tmp.name  parsed = parse_excel_file(temp_path, use_ai=use_ai, aggregate_sheets=aggregate)

    items = []
    for p in parsed:
        try:
            item = parsed_line_to_line_item(p)
            if item.cores and item.sqmm:
                items.append(item)
        except:
            continue

    st.subheader("Parsed Lines")
    st.write(f"Total parsed items: {len(items)}")

    # ---------------- SELECTION ---------------- #
    results = []
    for item in items:
        try:
            result = run_selection(item)
            results.append(result)
        except:
            continue

    # ---------------- SAFETY CHECK ---------------- #
    if len(items) != len(results):
        st.warning(f"⚠ Mismatch: {len(items)} items vs {len(results)} results")

    # ---------------- VALIDATION ---------------- #
    summary = validate_quote(items, results, discount_pct=discount_pct)

    st.subheader("Validation Summary")

    col1, col2, col3 = st.columns(3)
    col1.metric("Approved", summary.approved_count)
    col2.metric("Needs Review", summary.review_count)
    col3.metric("Blocked", summary.block_count)

    if summary.release_allowed:
        st.success("✅ Release Gate: OPEN — Quotation can be generated")
    else:
        st.error("❌ Release Gate: BLOCKED — Fix issues before generating")

    # ---------------- GENERATE OUTPUT ---------------- #
    if summary.release_allowed:

        if st.button("Generate Quotation"):

            config = QuoteConfig(
                quote_ref=quote_ref,
                quote_date="",
                client_name=client_name,
                project_name=project_name,
                section_label=section_label,
                section_title=section_title,
                discount_pct=discount_pct,
                generated_by=generated_by,
                approved_by=approved_by
            )

            try:
                output = generate_quotation(
                    items,
                    results,
                    summary,
                    config,
                    "quotation.xlsx"
                )

                if output.get("ok"):
                    with open("quotation.xlsx", "rb") as f:
                        st.download_button(
                            "Download Quotation",
                            f,
                            file_name="quotation.xlsx"
                        )
                else:
                    st.error(output.get("reason"))

            except Exception as e:
                st.error(f"Error generating quotation: {str(e)}")

    else:
        st.info("Fix validation issues to enable quotation generation.")
